import{a as b,i as n,S as L}from"./assets/vendor-ee72e1a4.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))i(r);new MutationObserver(r=>{for(const a of r)if(a.type==="childList")for(const c of a.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&i(c)}).observe(document,{childList:!0,subtree:!0});function e(r){const a={};return r.integrity&&(a.integrity=r.integrity),r.referrerPolicy&&(a.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?a.credentials="include":r.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function i(r){if(r.ep)return;r.ep=!0;const a=e(r);fetch(r.href,a)}})();const M=b.create({baseURL:"https://pixabay.com/"});async function f(o,t,e){try{const i={key:"44427326-e2b4a6eb28305d60c68b186c8",q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:e};return(await M.get("api/",{params:i})).data}catch(i){n.error({title:"Error",message:`${i}`,layout:2,displayMode:"once",backgroundColor:"#ef4040",progressBarColor:"#B51B1B",position:"topRight"})}}async function m(o){let t=o.map(e=>`<li class="gallery-item">  
      <a class="gallery-link" 
      href="${e.largeImageURL}">
      <img class="gallery-image" 
      src="${e.webformatURL}"
      alt="${e.tags}"/>
      </a> 
<div class="gallery-card-container">
<p><strong>Likes:</strong> ${e.likes}</p>
<p><strong>Views:</strong> ${e.views}</p>
<p><strong>Comments:</strong> ${e.comments}</p>
<p><strong>Downloads:</strong> ${e.downloads}</p>
<p><strong>Likes:</strong> ${e.likes}</p>
</div>
</li>`).join("");s.gallery.insertAdjacentHTML("beforeend",t),new L(".gallery a",{captions:!0,captionsData:"alt",captionDelay:250}).refresh()}function h(){s.loader.classList.remove("hidden")}function d(){s.loader.classList.add("hidden")}function B(){s.loadMoreBtn.classList.remove("hidden")}function p(){s.loadMoreBtn.classList.add("hidden")}function C(o,t){page>=t?(p(),t&&n.info({title:"The end!",message:"We're sorry, but you've reached the end of search results."})):B()}const s={form:document.querySelector(".form"),input:document.querySelector(".input"),button:document.querySelector("button"),gallery:document.querySelector(".gallery"),loader:document.querySelector(".loader"),loadMoreBtn:document.querySelector(".load-more-btn")};let l="",y=1,g=15,u=1;p();s.form.addEventListener("submit",async o=>{try{o.preventDefault(),l=o.target.elements.text.value.trim();let t=1;if(l===""){s.gallery.innerHTML=" ",n.warning({title:"Warning",message:"Please, enter the query.",backgroundColor:"#ef4040",layout:2,position:"topRight",displayMode:"once"});return}h(),s.gallery.innerHTML=" ";const e=await f(l,t,g);if(u=Math.ceil(e.totalHits/g),u===0){n.error({title:"Error",message:"Empty result",layout:2,displayMode:"once",backgroundColor:"#ef4040",progressBarColor:"#B51B1B",position:"topRight"}),d(),C(t,u);return}if(e.hits.length===0){n.error({message:"Sorry, there are no images matching your search query. Please try again!",layout:2,displayMode:"once",backgroundColor:"#ef4040",progressBarColor:"#B51B1B",position:"topRight"}),d(),s.form.reset();return}d(),s.form.reset(),m(e.hits),B()}catch(t){n.error({title:"Error",message:`${t}`,layout:2,displayMode:"once",backgroundColor:"#ef4040",progressBarColor:"#B51B1B",position:"topRight"})}});s.loadMoreBtn.addEventListener("click",async()=>{try{y++,p(),h();const o=await f(l,y,g);if(o.hits.length===0){n.error({message:"Sorry, there are no images matching your search query. Please try again!",layout:2,displayMode:"once",backgroundColor:"#ef4040",progressBarColor:"#B51B1B",position:"topRight"});return}m(o.hits)}catch(o){s.gallery.innerHTML=" ",n.error({title:"Error",message:`${o}`,layout:2,displayMode:"once",backgroundColor:"#ef4040",progressBarColor:"#B51B1B",position:"topRight"})}});
//# sourceMappingURL=commonHelpers.js.map
